spring:
  datasource:
    url: jdbc:mysql://localhost:3306/CNPayment?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class: com.mysql.cj.jdbc.Driver
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect
    hibernate.ddl-auto: create-drop
